# Generated by Django 2.2.12 on 2020-04-18 22:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('type_of_dish', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type of Dish')),
                ('photo_url', models.URLField(max_length=500, verbose_name='Photo URL')),
                ('occasion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Occasion')),
                ('ingredients', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), size=None, verbose_name='Ingredients')),
                ('description', models.TextField(verbose_name='Description')),
                ('instructions', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Instructions')),
                ('total_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Time')),
            ],
        ),
    ]
